---
title: "Profiling"
author: "ROBINE Thomas"
date: "8 juin 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# I. Introduction

In this document, we made some profiling tests in order to know which part of the code is the one that have the longest run time.
We, especially, put our focus on parts after the "model_function" call because this is obvious that the model run time is the code run time, which is 498160 milliseconds.

So, we profile our code using the profiling tool from RStudio and we obtaine a flame graph that we analyzed.
Here is the listing of all the calls made after the "model_function" call, that we know their origin. There are many calls that we don't know from what part they are called from.

# II. Calls' path from model_function and their source

call 1 : model_function -> do.call :  SticsOnR/R/stics_wrapper.R#118

call 2 : model_function -> do.call -> exists_sticks_exe : SticsOnR/R/stics_wrapper.R#642

call 3 : model_function -> do.call -> check_sticks_exe : SticsOnR/R/stics_wrapper.R#642

call 4 : model_function -> do.call -> check_sticks_exe -> suppressWarnings : SticsOnR/R/stics_exe_utilities.R#288

call 5 : model_function -> do.call -> check_sticks_exe -> suppressWarnings -> run_system_cmd : SticsOnR/R/stics_exe_utilities.R#288

call 6 : model_function -> do.call -> check_sticks_exe -> suppressWarnings -> run_system_cmd -> system2 : SticsOnR/R/run_system_cmd.R#19

call 7 : model_function -> check_sticks_exe : SticsOnR/R/stics_wrapper.R#131

call 8 : model_function -> check_sticks_exe -> suppressWarnings : SticsOnR/R/stics_exe_utilities.R#288

call 9 : model_function -> check_sticks_exe -> suppressWarnings -> run_system_cmd : SticsOnR/R/stics_exe_utilities.R#288

call 10 : model_function -> check_sticks_exe -> suppressWarnings -> run_system_cmd -> system2 : SticsOnR/R/run_system_cmd.R#19

call 11 : model_function -> parallel::makeCluster : SticsOnR/R/stics_wrapper.R#140

call 12 : model_function -> parallel::clusterCall : SticsOnR/R/stics_wrapper.R#143

call 13 : model_function -> %dopar% : SticsOnR/R/stics_wrapper.R#237

# III. Parallel's runs

Call | Average Run time (ms) | Average Global run time (ms) | Average Rate on run (%)
:----|:-------|:--------------|:---------------------|:---------------
prog | 207493 | - | - 
model_function | 70630 | 197613 | 95.24
1 | 173 | 15723 | 7.58
2 | 10 | 707 | 0.35
3 | 160 | 31900 | 15.37
4 | 160 | 31900 | 15.37
5 | 160 | 31853 | 15.35
6 | 160 | 34973 | 16.86
7 | 180 | 31900 | 15.37
8 | 180 | 31900 | 15.37
9 | 180 | 31853 | 15.35
10 | 180 | 34973 | 16.86
11 | 123 | 12056 | 5.81
12 | 810 | 79750 | 38.44
13 | 750 | 76790 | 37

# IV. Sequential's runs

Call | Average Run time (ms) | Average Global run time (ms) | Average Rate on run (%)
:----|:-------|:--------------|:---------------------|:---------------
prog | 210166 | - | - 
model_function | 83550 | 199810 | 95.07
1 | 143 | 15770 | 7.50
2 | 10 | 810 | 0.39
3 | 133 | 31966 | 15.21
4 | 133 | 31946 | 15.20
5 | 133 | 31933 | 15.19
6 | 133 | 34940 | 16.62
7 | 166 | 31900 | 15.21
8 | 166 | 31900 | 15.20
9 | 166 | 31853 | 15.19
10 | 166 | 34973 | 16.62
11 | 120 | 12053 | 5.73
12 | 790 | 80546 | 38.32
13 | 740 | 78650 | 37.42